name: Add Issues To Projects

on:
  issues:
    types: 
      - opened

jobs:
  add-issues:
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate_token
        uses: actions/create-github-app-token@v3
        with:
          app-id: ${{ secrets.ALPHA_BOT_ID }}
          private-key: ${{ secrets.ALPHA_BOT_PEM }}

      - name: Add Alpha Bug Issue To project
        uses: actions/add-to-project@v2
        with:
          github-token: ${{ steps.generate_token.outputs.token }}
          project-url: https://github.com/orgs/IceWhaleTech/projects/5
          labeled: alpha, bug
          label-operator: AND
          
      - name: Add App Request Issue To project
        uses: actions/add-to-project@v2
        with:
          github-token: ${{ steps.generate_token.outputs.token }}
          project-url: https://github.com/orgs/IceWhaleTech/projects/8
          labeled: "App Request"
          label-operator: AND
