# This is a basic workflow to help you get started with Actions

name: Move alpha bug to project

on:
  issues:
    types: 
      - opened

jobs:
  track_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate_token
        uses: actions/create-github-app-token@v3
        with:
          app-id: ${{ secrets.ALPHA_BOT_ID }}
          private-key: ${{ secrets.ALPHA_BOT_PEM }}

      - name: Add Issue To GitHub Projects Beta
        uses: actions/add-to-project@v2
        with:
          project-url: https://github.com/orgs/IceWhaleTech/projects/5
          github-token: ${{ steps.generate_token.outputs.token }}
          labeled: alpha, bug
          label-operator: AND
